#version 450
#extension GL_ARB_compute_variable_group_size: enable

layout (std430, binding = 0) buffer Pos {
	vec4 positions[];
};

layout (std430, binding = 1) buffer Vel {
	vec4 velocities[];
};

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

void main() {
	const float deltaTime = 0.1f;
	uint index = gl_GlobalInvocationID.x;
	positions[index] += velocities[index] * deltaTime;
	//velocities[index] *= 0.995f;
}
