#pragma once

enum class ShipTypes {SCOUT, CORVETTE, FRIGATE, CRUISER, BARGE, COUNT};

enum class Actions {THRUST, RETURN, BREAK, STEER_RIGHT, STEER_LEFT, SHOOT, COOL, MINE, UNLOAD, COUNT};

enum class Missions {MINE, DELIVER, DEFEND, ESCORT, COUNT};
